/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MateriasSlugRouteImport } from './routes/materias.$slug'
import { Route as QuizSlugQuizRouteImport } from './routes/quiz.$slug.$quiz'

const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasSlugRoute = MateriasSlugRouteImport.update({
  id: '/materias/$slug',
  path: '/materias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugQuizRoute = QuizSlugQuizRouteImport.update({
  id: '/quiz/$slug/$quiz',
  path: '/quiz/$slug/$quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/materias/$slug': typeof MateriasSlugRoute
  '/quiz/$slug/$quiz': typeof QuizSlugQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/materias/$slug': typeof MateriasSlugRoute
  '/quiz/$slug/$quiz': typeof QuizSlugQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/materias/$slug': typeof MateriasSlugRoute
  '/quiz/$slug/$quiz': typeof QuizSlugQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/desempenho' | '/materias/$slug' | '/quiz/$slug/$quiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/desempenho' | '/materias/$slug' | '/quiz/$slug/$quiz'
  id: '__root__' | '/' | '/desempenho' | '/materias/$slug' | '/quiz/$slug/$quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesempenhoRoute: typeof DesempenhoRoute
  MateriasSlugRoute: typeof MateriasSlugRoute
  QuizSlugQuizRoute: typeof QuizSlugQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias/$slug': {
      id: '/materias/$slug'
      path: '/materias/$slug'
      fullPath: '/materias/$slug'
      preLoaderRoute: typeof MateriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug/$quiz': {
      id: '/quiz/$slug/$quiz'
      path: '/quiz/$slug/$quiz'
      fullPath: '/quiz/$slug/$quiz'
      preLoaderRoute: typeof QuizSlugQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesempenhoRoute: DesempenhoRoute,
  MateriasSlugRoute: MateriasSlugRoute,
  QuizSlugQuizRoute: QuizSlugQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
